package phoupraw.mcmod.createsdelight.registry;

import net.minecraft.util.Identifier;
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;
import phoupraw.mcmod.createsdelight.CreateSDelight;

public final class CSDIdentifiers {
    public static final Identifier PAN = of("pan");
    public static final Identifier GRILL = of("grill");
    public static final Identifier SPRINKLER = of("sprinkler");
    public static final Identifier ITEM_GROUP = of("item_group");
    public static final Identifier PAN_FRIED_BEEF_PATTY = of("pan_fried_beef_patty");
    public static final Identifier THICK_PORK_SLICE = of("thick_pork_slice");
    public static final Identifier PAN_FRIED_PORK_SLICE = of("pan_fried_pork_slice");
    public static final Identifier THIN_PORK_SLICE = of("thin_pork_slice");
    public static final Identifier GRILLED_PORK_SLICE = of("grilled_pork_slice");
    public static final Identifier SUGAR_PORK = of("sugar_pork");
    public static final Identifier SUNFLOWER_OIL = of("sunflower_oil");
    public static final Identifier LEAVES_RICE = of("leaves_rice");
    public static final Identifier VANILLA = of("vanilla");
    public static final Identifier VANILLA_SWEET_ROLL = of("vanilla_sweet_roll");
    public static final Identifier BAMBOO_STEAMER = of("bamboo_steamer");
    public static final Identifier STEAMED_BUNS = of("steamed_buns");
    public static final Identifier SMART_DRAIN = of("smart_drain");
    public static final Identifier COPPER_TUNNEL = of("copper_tunnel");
    public static final Identifier MULTIFUNC_BASIN = of("multifunc_basin");
    public static final Identifier VERTICAL_CUTTER = of("vertical_cutter");
    public static final Identifier PRESSURE_COOKER = of("pressure_cooker");
    public static final Identifier COOKED_RICE = of("cooked_rice");
    public static final Identifier VEGETABLE_BIG_STEW = of("vegetable_big_stew");
    public static final Identifier MINCER = of("mincer");
    public static final Identifier SATIATION = of("satiation");
    public static final Identifier ROSE_MILK_TEA = of("rose_milk_tea");
    public static final Identifier BUCKETED_SUNFLOWER_OIL = of("bucketed_sunflower_oil");
    public static final Identifier BOTTLED_SUNFLOWER_OIL = of("bottled_sunflower_oil");
    public static final Identifier CORAL_COLORFULS = of("coral_colorfuls");
    public static final Identifier BEETROOT_SOUP = of("beetroot_soup");
    public static final Identifier TOMATO_SAUCE = of("tomato_sauce");
    public static final Identifier POPPY_RUSSIAN_SOUP = of("poppy_russian_soup");
    public static final Identifier EGG_LIQUID = of("egg_liquid");
    public static final Identifier EGG_SHELL = of("egg_shell");
    public static final Identifier EGG_DOUGH = of("egg_dough");
    public static final Identifier CRUSHED_ICE = of("crushed_ice");
    public static final Identifier WHEAT_BLACK_TEA = of("wheat_black_tea");
    public static final Identifier ICED_MELON_JUICE = of("iced_melon_juice");
    public static final Identifier MELON_JUICE = of("melon_juice");
    public static final Identifier THICK_HOT_COCOA = of("thick_hot_cocoa");
    public static final Identifier SKEWER = of("skewer");
    public static final Identifier BASIN = of("basin");
    public static final Identifier SKEWER_PLATE = of("skewer_plate");
    public static final Identifier SALT = of("salt");
    public static final Identifier KELP_ASH = of("kelp_ash");
    public static final Identifier JELLY_BEANS = of("jelly_beans");
    public static final Identifier JELLY_BEANS_CAKE = of("jelly_beans_cake");
    public static final Identifier YEAST = of("yeast");
    public static final Identifier PASTE = of("paste");
    public static final Identifier CAKE_BASE = of("cake_base");
    public static final Identifier CAKE_BASE_SLICE = of("cake_base_slice");
    public static final Identifier SWEET_BERRIES_CAKE = of("sweet_berries_cake");
    public static final Identifier BASQUE_CAKE = of("basque_cake");
    public static final Identifier RAW_BASQUE_CAKE = of("raw_basque_cake");
    public static final Identifier SWEET_BERRIES_CAKE_S = of("sweet_berries_cakes");
    public static final Identifier BROWNIE = of("brownie");
    public static final Identifier APPLE_CREAM_CAKE = of("apple_cream_cake");
    public static final Identifier SUNFLOWER_KERNELS = of("sunflower_kernels");
    public static final Identifier PUMPKIN_OIL = of("pumpkin_oil");
    public static final Identifier BUCKETED_PUMPKIN_OIL = of("bucketed_pumpkin_oil");
    public static final Identifier OVEN = of("oven");
    public static final Identifier APPLE_PASTE = of("apple_paste");
    public static final Identifier APPLE_CAKE = of("apple_cake");
    public static final Identifier CARROT_CREAM_CAKE = of("carrot_cream_cake");
    public static final Identifier MASHED_PATATO = of("mashed_potato");
    public static final Identifier JELLY_BEANS_CAKE_0 = of("jelly_beans_cake_0");
    public static final Identifier SWEET_BERRIES_CAKE_0 = of("sweet_berries_cake_0");
    public static final Identifier SWEET_BERRIES_CAKE_S_0 = of("sweet_berries_cake_s_0");
    public static final Identifier RAW_BASQUE_CAKE_0 = of("raw_basque_cake_0");
    public static final Identifier BROWNIE_0 = of("brownie_0");
    public static final Identifier APPLE_CREAM_CAKE_0 = of("apple_cream_cake_0");
    public static final Identifier CARROT_CREAM_CAKE_0 = of("carrot_cream_cake_0");
    public static final Identifier IRON_BOWL = of("iron_bowl");
    public static final Identifier SMALL_CHOCOLATE_CREAM_CAKE = of("small_chocolate_cream_cake");
    public static final Identifier MEDIUM_CHOCOLATE_CREAM_CAKE = of("medium_chocolate_cream_cake");
    public static final Identifier BIG_CHOCOLATE_CREAM_CAKE = of("big_chocolate_cream_cake");
    public static final Identifier CHOCOLATE_PASTE = of("chocolate_paste");
    public static final Identifier CHOCOLATE_CAKE_BASE = of("chocolate_cake_base");
    public static final Identifier IRON_BAR_SKEWER = of("iron_bar_skewer");
    public static final Identifier CHOCOLATE_ANTHEMY_CAKE = of("chocolate_anthemy_cake");
    public static final Identifier CAKE_BLUEPRINT = of("cake_blueprint");
    public static final Identifier PRINTED_CAKE = of("printed_cake");
    public static final Identifier CREAM = of("cream");
    public static final Identifier CAKE_INGREDIENT = of("cake_ingredient");
    public static final Identifier CHOCOLATE_BLOCK = of("chocolate_block");
    public static final Identifier HONEY = of("honey");
    public static final Identifier CAKE_OVEN = of("cake_oven");
    public static final Identifier PUMPKIN = of("pumpkin");
    public static final Identifier MELON = of("melon");
    public static final Identifier HAY = of("hay");
    public static final Identifier PREDEFINED_CAKE = of("predefined_cake");
    public static final Identifier CHOCOLATE = of("chocolate");
    public static final Identifier BUCKETED_EGG_LIQUID = of("bucketed_egg_liquid");
    public static final Identifier BOTTLED_EGG_LIQUID = of("bottled_egg_liquid");
    public static final Identifier IN_PROD_CAKE = of("in_prod_cake");
    public static final Identifier SHRINKING_CAKE = of("shrinking_cake");
    public static final Identifier MOVING_CAKE = of("moving_cake");
    public static final Identifier VOXEL_MAKER = of("voxel_maker");
    public static final Identifier MADE_VOXEL = of("made_voxel");
    public static final Identifier EMPTY = of("empty");
    public static final Identifier APPLE_JAM = of("apple_jam");
    public static final Identifier BUCKETED_APPLE_JAM = of("bucketed_apple_jam");
    public static final Identifier WHEAT_PASTE = of("wheat_paste");
    public static final Identifier BUCKETED_WHEAT_PASTE = of("bucketed_wheat_paste");
    public static final Identifier WHEAT_CAKE_BASE_BLOCK = of("wheat_cake_base_block");
    public static final Identifier BUCKETED_CREAM = of("bucketed_cream");
    public static final Identifier BUTTER_NUGGET = of("butter_nugget");
    public static final Identifier BUTTER_INGOT = of("butter_ingot");
    public static final Identifier BUTTER_BLOCK = of("butter_block");
    @Contract("_ -> new")
    @ApiStatus.Internal
    public static @NotNull Identifier of(String path) {
        return new Identifier(CreateSDelight.MOD_ID, path);
    }
    private CSDIdentifiers() {
    }
}
